apiVersion: apps/v1 # versão da API a ser usada; usar o comando $ kubectl api-resources para saber qual apiVersion utilizar.
kind: Deployment  # Este campo kind informa ao Kubernetes que está definindo um Deployment object
metadata:
  name: hello-deploy  # Nome do Deployment. Deve ser um nome DNS válido
spec:
  # replicas: 10
  replicas: 5 # Número de réplicas de pod para implantar e gerenciar
  selector:
    matchLabels:
      app: hello-world # Label usado para selecionar os pods
  revisionHistoryLimit: 5 # Quantas versões/ReplicaSets mais antigos devem ser mantidos para Rollbacks
  progressDeadlineSeconds: 300  # Informa ao Kubernetes quanto tempo esperar durante uma atualização(rollout) para que cada nova réplica fique online
  minReadySeconds: 10 # iniciando os novos pods e aguardando 10 segundos antes de passar para os próximos dois
  strategy: # Este bloco controla como as atualizações acontecem
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template: # Pod Template
    metadata:
      labels:
        app: hello-world # Label aplicado aos pods
    spec:
      containers:
      - name: hello-pod
        image: nigelpoulton/k8sbook:2.0
        # image: nigelpoulton/k8sbook:2.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 128Mi
            cpu: 0.1
