apiVersion: v1
kind: Service
metadata:
  name: svc-test
  labels:
    chapter: services # esta label apenas identifica o serviço e não os Pod.
spec:
# ipFamilyPolicy: PreferDualStack
# ipFamilies:
# - IPv4
# - IPv6
  type: NodePort
  ports:
  #- port: 8080
  - port: 9090
    nodePort: 30001
    targetPort: 8080
    # targetPort: 9090
    protocol: TCP
  selector:
    chapter: services
